### ISSUE TITLE
inability_to_walk (and similar) mapping

### ISSUE THREAD

**Issue by pipliggins** [globaldothealth/isaric#104]
At the moment, in the SA parser, inability_to_walk is mapped as a boolean i.e. True = Unable to walk, and False = No inability walking. However, there are 3 different ways this is being mapped, according to whether the data in various fields is:
* boolean (Y/N)
* scale of 1-5 (none, slight, moderate, severe, unable)
* scale of 1-4 (no difficulty, some difficulty, lots of difficulty, unable).

At the moment, values 2->5 on the scales are being mapped 'True', i.e. indicating 'I am unable to walk'. This seems inappropriate as a slight inability to walk is being given the same weight as someone who is completely unable. We should also bear in mind that a single attribute should be mapped in the same type (i.e. either boolean, value or text) throughout a single parser (and preferably across all the datasets) to enable efficient data querying. Options to resolve this are:
1. Keep things as they are, mapped as a boolean and make it clear in the mapping guide and to users that 'inability to walk' can mean only a slight difficulty.
2. As above, but rename the attribute to e.g. 'difficulty_walking', to make it clearer that True values may indicate a patient who can walk, but not easily, as well as those who are unable.
3. Map the attribute to 'text' rather than 'is_present', and use the descriptions from the form (yes, no, slight, moderate etc) as the returned value (this will make data querying difficult as this is essentially free text, where the wording of the text will depend on the field the data is pulled from)
4. Create a new value map where everything is converted to a 1-5 scale. Y/N would map to 5/1 respectively, and the 1-4 scale would miss out 3. We can either return a number, or map these onto our own 'None, slight, moderate, severe, unable' set of return values.

We should decide on a general approach to this kind of issue, as it's likely to crop up in other datasets.

**Comment by pipliggins** [comment]
I think my preference would be for option (4), but it might be worth discussion how to approach this kind of issue in the meeting. Is it important, generally, to maintain the 'scale' level of info where it has been provided? Or are we okay collapsing things down as long as it is made clear what that True/False value entails?

**Comment by ekamau** [comment]
I have been looking at the 'walking' fields:
The source South Africa dataset has values '1,2,3,4,5' or '1,2,3,4' in
these columns, which means there is an existing scale .. I think.
According to the data dictionary, the values refer to:
1, No - no difficulty|2, Yes - some difficulty|3, Yes - a lot of
difficulty|4, Cannot do at all
1, I have no problems in walking about|2, I have slight problems in walking
about|3, I have moderate problems in walking about|4, I have severe
problems in walking about|5, I am unable to walk about

Probably try options 2 based on this information:
rename to 'difficulty_walking' and map to true  / false; where 2/3/4/5 =
true and 1 = false

**Comment by sadiekelly** [comment]
A few thoughts on the inability/difficulty walking mapping issue:
The boolean responses are generally captured as a symptom at admission, whereas the scaled responses are from follow up. The exception are the boolean responses from S.Africa which are captured on the follow up survey but refer to the period of time from illness onset to covid-19 diagnosis. 
Follow up responses include both a question asking about difficulty walking or climbing steps as well as the mobility responses from the EQ5D-5L questionnaire.
I feel a bit concerned about mapping 'no inability to walk' to indicate no difficulty at all in walking (from option 4) as the only responses available were yes/no and someone could experience difficulty but not inability to walk so would answer No here. 
Could we create two variables from this data, and keep the scaled responses? 
1. Inability to walk where Inability to walk = Y also includes Cannot do at all and I was/am unable to walk about
2. Difficulty walking where we keep and match the scaled responses;
                                           No difficulty = I had/have no problems walking about from EQ5D
                                           Some difficulty = slight problems walking about (EQ5D)
                                           A lot of difficulty = moderate/severe problems walking about (EQ5D)
The problem still remains where to map Inability to walk = N or U though. Would be good to discuss more later on.

**Comment by abhidg** [comment]
From 27/3 meeting, this will be resolved by splitting inability_to_walk into a boolean indicator (inability_to_walk) and a scale (inability_to_walk_scale). The scale will be from 1 to 4, with slight and moderate from 1-5 scale being mapped to 'some difficulty' in the 1-4 scale.

Generally agreed with such issues, we will try to keep as much data as we can, but if there are multiple scales, will combine them as we think appropriate, but record this in the mapping guide.

**Comment by ekamau** [comment]
Sounds good.
Should these changes be made in the schema or only in the parsers, where
applicable?

**Comment by pipliggins** [comment]
Added to mapping guide

**Comment by pipliggins** [comment]
All parsers now follow this approach, closing as completed.
