### ISSUE TITLE
Review dates in schemas

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/isaric#118]
Subject table should only have dates that are the same across all visits, so consider moving admission date to visit.

**Comment by pipliggins** [comment]
This may be partially linked to switching the required date in Subject from enrolment date (which should be the same across visits, you're only enrolled once) -> admission date which varies. So maybe have just enrolment date in subject, and then merge admission + start date in visit (as these are the same thing)?

**Comment by ekamau** [comment]
Are you suggesting we go with one date per table? that's sensible.

Some datasets, very few, had enrollment date & admission date. For those
without enrollment date, we decided to make enrollment date optional field
...
Start date has mostly been the admission date or the admission date
hierarchy ... in most cases. it's sensible to merge start date and
admission date ..

Then it ends up that admission date / admission date hierarchy is used as
the primary date fields in subject and visits table?

**Comment by abhidg** [comment]
Fixed by ensuring either enrolment date or earliest admission date is required
