### ISSUE TITLE
Pre-admission vaccination and medication records

### ISSUE THREAD

**Issue by pipliggins** [globaldothealth/isaric#130]
Currently we are not encoding vaccinations and meds pre-admission - see discussion in #126

**Comment by pipliggins** [comment]
We have an attribute 'phase' in the visit table which I think possibly was to account for cases like this? Originally the thought was because each 'visit' is an encounter with a healthcare professional, so there could be multiple visits per subject. Having the pre-admission vaccination and chronic meds record as an individual visit, with 'phase' = pre-admission might work?

**Comment by abhidg** [comment]
From discussion on 25/10 might be useful to have pre-admission oxygen therapy and ventilation, others are present in less than 5 studies.

**Comment by pipliggins** [comment]
Vaccinations have been added to the Subject table, with dates.

**Comment by abhidg** [comment]
Workstream discontinued, closing as wontfix
