### ISSUE TITLE
(isaric_washington): Searching multiple rows for dates

### ISSUE THREAD

**Issue by pipliggins** [globaldothealth/isaric#131]
In the Washington dataset, the admission date is on a different row to the visit observations + outcomes. 

The dataset is structured so that the outcome date is calculated as admission date + length of hospital stay; but the two fields for this are on different rows with no suitable alternatives. This means all the data has no outcome date. How can we address this?

**Comment by ekamau** [comment]
agreed! sounds good ..

**Comment by pipliggins** [comment]
Closed as Not Planned; data has been modified to include the admission date on every row for each subject, as with other parsers.
