### ISSUE TITLE
Modify observation schema to take into account value types and limits

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/isaric#152]
e.g. heart_rate_bpm should be between 0 - 500, or inability_to_walk_scale should be from 1 to 5

**Comment by ekamau** [comment]
nice. is this part of parser validation or data validation? or it covers both?

**Comment by abhidg** [comment]
> nice. is this part of parser validation or data validation? or it covers both?

Both. At the parser level, the new schema will checkn that observations are assigned the correct type (value, is_present or text), and at the data level, it will check ranges (oxygen_saturation_percent from 1 to 100).
