### ISSUE TITLE
Miscellaneous bugs/inconsistencies

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/isaric#178]
- [x] dob_year present in all parsers
- [x] outcome = recovered, is this actually recovered or discharged alive
- [x] musculoskeletal pain in all parsers
- [x] pre-admission vs admission phase, this might be used inconsistently
- [x] consider merging experimental_agent fields into others and recording
  experimental agent in study metadata
- [ ] other fields (via @rbevansp) -- currently other fields in the schema
  have inconsistent meanings. From the POV of our schema, it should mean
  the fields that we did not capture. In contrast, data dictionary other
  fields refer to the fields that they did not capture, which is different
  from our set, since we typically have fewer schema items compared to many
  data dictionaries. Suggest dropping treatment_other / comorbidity_other
  unless we can resolve this.
- [x] Chloroquine/Hydroxychloroquine is present in multiple places. Suggest
  only one place for it -- antimalarials and update parsers accordingly. If
  chloroquine is an experimental agent, that could be tracked in study
  metadata
- [x] Multiple admission phases, are they allowed? e.g. in idor-brazil.
- [x] Check for consistency between lab work vs microbiology lab worker in CRFs
- [x] treatment of checkbox fields may be inconsistent with earlier parsers

**Comment by ekamau** [comment]
nice!
Is study metadata part of the parser structure?

**Comment by abhidg** [comment]
No, we will record it in a separate table that will include metadata 
from all parsers

**Comment by ekamau** [comment]
so far, in the parsers in main branch: dob_year is only missing in the washington parser, which has no age units and ages have a character '>', e.g., >90

**Comment by abhidg** [comment]
Workstream discontinued, closing as wontfix
