### ISSUE TITLE
Add vaccination status to data

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/isaric#186]
1. subject.vaccinated_covid19_dates (list)
2. subject.vaccinated_covid19 (boolean)

Do not include data from followup as it is noisy

**Comment by ekamau** [comment]
Is the requirement to add information on the number of vaccine shots - quantity? or boolean yes/no if someone had/had not received vaccine(s) at the time of data collection?

**Comment by ekamau** [comment]
add to schemas and guide ..
only at admission

**Comment by ekamau** [comment]
Added in #197
