### ISSUE TITLE
Check behaviour of super types

### ISSUE THREAD

**Issue by pipliggins** [globaldothealth/isaric#190]
As with the works_lab super type, some supertypes may not have a non-exhaustive list of subtypes. Subtypes which are not mapped may or may not be true, therefore the super type cannot be definitively be mapped to false. 

Supertypes should be true or null except for exhaustive lists (e.g. cough) or where there is a general attribute (e.g. oxygen_therapy where a general oxygen_therapy attribute is present).

For e.g. oxygen_therapy:
```
[visit.treatment_oxygen_therapy]
    combinedType = "any"
    fields = [
      { field = "overall_oxygen_cmoccur", values = { 1 = true, 0 = false } }, # A general field
      { field = "can_oxy_ther", values = { 1 = true} },             # subtypes which have their own attributes
      { field = "overall_invasive_proccur", values = { 1 = true } },
      { field = "inv_vent", values = { 1 = true } },
      { field = "overall_noninvasive_proccur", values = { 1 = true } },
      { field = "non_inv_vent", values = { 1 = true } },
      { field = "overall_extracorp_prtrt", values = { 1 = true } },
    ]

[visit.treatment_invasive_ventilation]
    combinedType = "any"
    fields = [
      { field = "overall_invasive_proccur", values = { 1 = true, 0 = false } },
      { field = "inv_vent", values = { 1 = true, 0 = false } },
    ]
```

**Comment by ekamau** [comment]
Something else - how do you reconcile different start dates for attributes - observation table - that form a supertype?
example:

start_date = { field = "myalgia_cestdat_v2" } - 'muscle pain'
start_date = { field = "jointpain_cestdat_v2" } - 'joint pain'

what would be the start date for the supertype? - one of the two above? a combinedType = "all", a combinedType = "firstNonNull"?

**Comment by abhidg** [comment]
A combinedType = “min" should work to pick the earlier date.

On 19 Oct 2023, at 23:59, Everlyn Kamau ***@***.***> wrote:



Something else - how do you reconcile different start dates for attributes - observation table - that form a supertype?
example:

start_date = { field = "myalgia_cestdat_v2" } - 'muscle pain'
start_date = { field = "jointpain_cestdat_v2" } - 'joint pain'

what would be the start date for the supertype? - one of the two above? a combinedType = "all", a combinedType = "firstNonNull"?

**Comment by ekamau** [comment]
super!

**Comment by abhidg** [comment]
Workstream discontinued, closing as wontfix
