### ISSUE TITLE
isaric-ccpuk: use combinedType=list for ethnicity field

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/isaric#22]
With the new combinedType=list field type (#20), ethnicity should be ported to use this, as it's a multi-choice field in the CCPUK CRF.

**Comment by ekamau** [comment]
looking at ethnicity: 
In the CCPUK dataset, there are ten ethnic columns 'ethnic__1' to 'ethnic__10'. Plus 'other_ethnicity'. There are three values in the ten 'ethnic__': '0', '1' and 'nan'. What do they represent?. For instance, 'ethnic___1' for ethnic group "Arab" has '0' (36452 rows), '1' (193 rows) and 'nan' (290652 rows). Does '0' represent Arab ethnic group? what does '1' represent then?

**Comment by ekamau** [comment]
A lot of other information on ethnicity is text - where ethnic == 'other'. How do we port this, as a single field?

**Comment by ekamau** [comment]
the field 'other_ethnic' in CCPUK is technically part of ethnicity.

**Comment by ekamau** [comment]
submitted a pull request for this. review and check for correctness. I am still not sure how to add the 'other' ethnicity descriptions as a ';' or ',' delimited list. I will come back to this.
