### ISSUE TITLE
ETL ISARIC RAPID

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/isaric#35]

**Comment by ekamau** [comment]
Mappings for visit and subject tables are ready. next step is to format to .json format?

**Comment by pipliggins** [comment]
Subject and Visit tables in toml format, just the observations table left to add

**Comment by ekamau** [comment]
Working on the observations table as of yesterday - in progress!

**Comment by ekamau** [comment]
observations table now in branch 'rapid-observations'
