### ISSUE TITLE
Start mapping observations CCPUK

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/isaric#44]

**Comment by ekamau** [comment]
Ongoing. 
Things to sort out / add: 'phase' of observation; 'date' of observation; should we include observations in previous reinfection / hospitalization episode(s)? observations before hospitalization?
should there be 'end date' of observation?

**Comment by ekamau** [comment]
Update - posted observations table mappings for CCPUK

**Comment by ekamau** [comment]
ccpuk observations in branch ccpuk_observations
