### ISSUE TITLE
What is end date in visit?

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/isaric#45]
Assuming subjid = visit_id always?

**Comment by ekamau** [comment]
Yes, need to establish if subjid = visit_id is the same in other datasets.

**Comment by pipliggins** [comment]
In this case, do we need both end_date and date_outcome? If so, what's the difference between the two?

**Comment by ekamau** [comment]
I think date_outcome was one of the options/mapping fields for end_date ... there might be other options/fields for end_date ...

**Comment by pipliggins** [comment]
It looks like in the schema at the moment both are attribute options. Maybe it makes sense to have end_date as the only attribute, with date_outcome (dsstdtc) as the preferred field for it? I guess if the visit is referring to admission/followup there won't a outcome date to record, the end date will come from somewhere else...

**Comment by ekamau** [comment]
Sounds sensible ..

**Comment by abhidg** [comment]
Fixed by removing end_date in 4736edaa327241856630a25fc289b1270349a6ee
