### ISSUE TITLE
Create a mapping guide

### ISSUE THREAD

**Issue by pipliggins** [globaldothealth/isaric#80]
Create a mapping guide (could also use the wiki) which will have best practices for combinedTypes etc

**Comment by ekamau** [comment]
Nice idea. Where is the wiki?

**Comment by pipliggins** [comment]
I think for the moment using the docs in adtl (https://github.com/globaldothealth/adtl/blob/main/docs/specification.md) is where we're storing this info - although it's probably worth either having a copy or a subset in this repo too as this is where the parsers are being written.

**Comment by abhidg** [comment]
adtl is for generic parser documentation, like syntax of the specification. Mostly, I was thinking of capturing stuff like: how to do date hierarchies, what phases mean, etc; that is specific to clinical datasets.

**Comment by pipliggins** [comment]
Closed as completed by merging the mapping-guide-edits branch.
