### ISSUE TITLE
Distinction between 'has_hiv_art' and 'has_hiv_suppression'

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/isaric#85]
> I wonder if there is really a distiction between 'has_hiv_art' and 'has_hiv_suppression' .. if '_hiv_art' falls within '_hiv_suppression' ... the idea being that ART is part of hiv suppression?

_Originally posted by @ekamau in https://github.com/globaldothealth/isaric/pull/84#discussion_r1119034309_

**Comment by ekamau** [comment]
I realized the South Africa data has fields for 'hiv_art' and 'hiv_suppression'. So we might as well keep the two attributes - they might mean different things!
