### ISSUE TITLE
Tracking multiple drugs in treatment types

### ISSUE THREAD

**Issue by pipliggins** [globaldothealth/isaric#86]
E.g. at the moment for corticosteroids, we have treatment_corticosteroid as a boolean, but the only treatment we store information about is dexamethasone (treatment_dexamthasone). Suggest changing the boolean 'treatment_dexamethasone' to a combinedType list field similar to ethnicity, so we also track Methylprednisone, Prednisone and then have 'other' as a free text field within the combined type.

Repeat for similar fields - e.g. antiviral, experimental agents.

**Comment by ekamau** [comment]
Good issue!. could we have it in the schema? then we can easily add it in
the parser ..
