### ISSUE TITLE
visit mapping schema

### ISSUE THREAD

**Issue by rbevansp** [globaldothealth/isaric#95]
TL;DR - Should "treatment_oxygen_mechanical_support" be removed from the visit schema?

Is the attribute "treatment_oxygen_mechanical_support" perhaps redundant? 
I think all invasive & noninvasive oxygen treatment are types of oxygen mechanical support (I may be wrong about this!)
In the schema there are separate attributes for 
(1) treatment_invasive_ventilation
(2) treatment_invasive_ventilation.

**Comment by ekamau** [comment]
In the South Africa data, there is a matching / mapping field for
'mechanical support', plus both noninvasive and invasive ventilation.
It could be that the three have different meanings, clinically.

We might as well keep it 'mechanical support' in the schema ... perhaps
other studies also recorded mechanical support ..
